flowchart TD
    DeviceFiltersModel["DeviceFilters"] --> DeviceOption["DeviceFilterOption"]
    DeviceFiltersModel --> TagOption["TagFilterOption"]
    DeviceFilterOptionsModel["DeviceFilterOptions"] --> DeviceStatus
    DeviceFilterOptionsModel --> DeviceType
