flowchart LR
    Client["Client App"] --> RestAPI["REST or GraphQL API"]
    RestAPI --> MapperCreate["OrganizationMapper"]
    MapperCreate --> Service["Organization Service"]
    Service --> Repo["Mongo Repository"]
    Repo --> DB["MongoDB"]
    DB --> Repo
    Repo --> Service
    Service --> MapperResponse["OrganizationMapper"]
    MapperResponse --> RestAPI
    RestAPI --> Client
