flowchart TD
    client_core_config["client_core_config"] -->|provides config to| client_core_controller["client_core_controller"]
    client_core_config -->|provides config to| client_core_service_agentregistration_processor["client_core_service_agentregistration_processor"]
    client_core_config -->|provides config to| client_core_listener["client_core_listener"]
    client_core_config -->|provides config to| client_core_service_agentregistration_transformer["client_core_service_agentregistration_transformer"]