flowchart TD
    IntegratedToolTypes["IntegratedToolTypes"]
    ToolCredentials["ToolCredentials"]
    data_mongo_document_tool["data_mongo_document_tool"]
    data_mongo_document_toolagent["data_mongo_document_toolagent"]
    data_mongo_document_tool_filter["data_mongo_document_tool_filter"]
    data_mongo_repository_tool["data_mongo_repository_tool"]
    api_lib_dto_tool["api_lib_dto_tool"]
    api_service_core_datafetcher["api_service_core_datafetcher"]
    management_service_core_controller_integratedtool["management_service_core_controller_integratedtool"]
    stream_service_core_service["stream_service_core_service"]

    IntegratedToolTypes -->|referenced by| data_mongo_document_tool
    IntegratedToolTypes -->|referenced by| data_mongo_document_toolagent
    IntegratedToolTypes -->|referenced by| data_mongo_document_tool_filter
    IntegratedToolTypes -->|referenced by| data_mongo_repository_tool
    IntegratedToolTypes -->|referenced by| api_lib_dto_tool
    IntegratedToolTypes -->|referenced by| api_service_core_datafetcher
    IntegratedToolTypes -->|referenced by| management_service_core_controller_integratedtool
    IntegratedToolTypes -->|referenced by| stream_service_core_service
    ToolCredentials -->|referenced by| data_mongo_document_tool
    ToolCredentials -->|referenced by| data_mongo_document_toolagent
    ToolCredentials -->|referenced by| data_mongo_repository_tool
    ToolCredentials -->|referenced by| stream_service_core_service