flowchart LR
    MongoConfig --> MongoConfiguration
    MongoConfig --> ReactiveMongoConfiguration
    MongoConfiguration --> MappingMongoConverter
    ReactiveMongoConfiguration --> ReactiveRepositories
