flowchart TD
    UserDoc["User"] --> AuthUserDoc["AuthUser"]
    OrganizationDoc["Organization"]
    DeviceDoc["Device"]
    MachineTagDoc["MachineTag"]
    CoreEventDoc["CoreEvent"]
    ExternalEventDoc["ExternalApplicationEvent"]
    OAuthClientDoc["MongoRegisteredClient"]
    OAuthTokenDoc["OAuthToken"]
    TagDoc["Tag"]
