flowchart TD
    Client --> Gateway
    Gateway --> ExternalAPI
    Gateway --> ApiCore

    ApiCore --> Authz
    ApiCore --> Mongo
    ApiCore --> Redis
    ApiCore --> Pinot

    Authz --> Mongo
    Authz --> JWT

    Stream --> Kafka
    Stream --> Cassandra
    Stream --> Pinot

    Management --> Redis
    Management --> NATS
