flowchart LR
    LogStorage["Audit Log Storage"] --> SummaryQuery["Summary Query"]
    LogStorage --> DetailsQuery["Details Query"]

    SummaryQuery --> LogEventDTO["LogEvent"]
    DetailsQuery --> LogDetailsDTO["LogDetails"]
