import { defineConfig, globalIgnores } from 'eslint/config';

import next from './eslint-config/next.js';
import prettierCompat from './eslint-config/prettier-compat.js';
import storybook from './eslint-config/storybook.js';
import tests from './eslint-config/tests.js';

/*
 * The fast pass — no type-aware rules. This is what the editor loads and what
 * an agent runs dozens of times per task (lint-spec §7.2). The type-aware half
 * lives in eslint.types.mjs and extends this file, so there is one source of
 * truth, not two.
 *
 * Splitting them is not only about speed: `eslint . --fix` with the type-aware
 * layer on gets OOM-killed at an 8 GB heap on this library, and every rule with
 * a fixer here (import order, unused imports, prefer-const, dot-notation) is
 * type-free anyway.
 *
 * The library ships Next-aware components (embed shims around next/image,
 * next/link) and keeps `next` as a devDependency, so it takes the `next` layer
 * rather than the plain `react` one — that is what makes rules like
 * @next/next/no-img-element meaningful here.
 *
 * Imports are relative rather than
 * `@flamingo-stack/openframe-frontend-core/eslint-config/...` so the package
 * does not have to be installed into its own node_modules to lint itself, and
 * so a stale published copy can never shadow the working tree.
 *
 * Order is load-bearing: prettierCompat last, because its only job is to win
 * (§2.3).
 */
export default defineConfig([
  ...next,
  ...storybook,
  ...tests,

  globalIgnores([
    // SVGR output — regenerated by `npm run generate:icons`, never hand-edited.
    'src/components/icons-v2-generated/**',
  ]),

  {
    // Every extension the Next preset matches, not just ts/tsx: the rule prints
    // its "Pages directory cannot be found" warning from inside `create()`, so a
    // single unconfigured `.js` file in the repo is enough to emit it. Off since
    // 2026-08-24 — this is a library, there is no pages/ or app/ directory for
    // it to compare hrefs against, and there never will be.
    name: 'openframe-frontend-core/no-pages-dir',
    files: ['**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}'],
    rules: { '@next/next/no-html-link-for-pages': 'off' },
  },

  {
    // Three deliberate, permanent dependency-array decisions. Every other
    // `exhaustive-deps` finding in this repo was fixed (57 -> 3) — these are the
    // ones with no source-level expression, so they are declared here where the
    // reason is reviewable. A named block is the ONLY place an unfixed finding
    // may live in this repo — see CLAUDE.md:
    //
    //   - chat-message-list: `useImperativeHandle(ref, () => scrollRef.current,
    //     [scrollRef, isLoading])`. The factory does not READ `isLoading`, so
    //     the rule calls it unnecessary — but it is what forces the handle to be
    //     republished when the loading branch unmounts. Without it a parent that
    //     mounted the list while loading held `null` for the component's life.
    //   - use-auto-limit-tags: `placeholder` is not read either. It is rendered
    //     into an off-screen measuring node whose `offsetWidth` the callback
    //     DOES read, so the text changing must retrigger the measurement. No
    //     dependency array can say "re-run when this DOM measurement changes".
    //   - use-outer-or-default: the hook FORWARDS its caller's `deps` array to
    //     `useMemo`. `exhaustive-deps` cannot verify a forwarded array and
    //     `use-memo` (off for this file above) requires a literal.
    name: 'openframe-frontend-core/deliberate-dependency-arrays',
    files: [
      'src/components/chat/chat-message-list.tsx',
      'src/hooks/ui/use-auto-limit-tags.ts',
      'src/contexts/use-outer-or-default.ts',
    ],
    rules: { 'react-hooks/exhaustive-deps': 'off' },
  },

  {
    // `static-components` fires on `const Icon = resolveIcon(name); <Icon/>`.
    // The rule's target is a component DECLARED inside render (whose state
    // resets every time the parent renders); these five sites instead LOOK UP
    // an existing module-level component in an icon registry. The component is
    // stable for a stable name, and a changed name SHOULD remount. There is no
    // way to write a name-driven registry lookup that the rule accepts short of
    // a hand-written switch over every icon.
    name: 'openframe-frontend-core/icon-registry-lookup',
    files: [
      'src/components/chat/entity-cards/task-type-icon.tsx',
      'src/components/features/os-type-badge.tsx',
      'src/components/icon-display.tsx',
      'src/components/ui/file-manager/file-icon.tsx',
    ],
    rules: { 'react-hooks/static-components': 'off' },
  },

  {
    // `useOuterOrDefault(context, factory, deps)` FORWARDS its caller's
    // dependency array to `useMemo` — that is the hook's entire contract, and
    // it is documented at length in the file. `react-hooks/use-memo` requires
    // an array literal so it can verify the deps statically, which no
    // deps-forwarding wrapper can ever satisfy, and the rule has no
    // `additionalHooks`-style escape.
    name: 'openframe-frontend-core/deps-forwarding-hook',
    files: ['src/contexts/use-outer-or-default.ts'],
    rules: { 'react-hooks/use-memo': 'off' },
  },

  {
    // `ColumnMeta<TData, TValue>` is a declaration MERGE into
    // @tanstack/react-table. TypeScript requires every declaration of an
    // interface to carry identical type parameters — names included (TS2428) —
    // so the two cannot be renamed to `_TData` / `_TValue`, and none of the
    // members this repo adds happens to reference them. Verified by trying it:
    // the rename fails to compile. There is no source-level fix.
    name: 'openframe-frontend-core/declaration-merge-type-params',
    files: ['src/components/ui/data-table/types.ts'],
    rules: { '@typescript-eslint/no-unused-vars': 'off', 'unused-imports/no-unused-vars': 'off' },
  },

  {
    // The ONE namespace import left in src. `import * as IconsV2` is not a
    // shorthand here — the module IS the registry: `resolveFromLibrary` builds
    // candidate names from a runtime string ("ai-agent" -> `AIAgentIcon`) and
    // looks them up, so the whole export map has to be addressable by name.
    // Named imports cannot express that, and every icon ends up in the bundle
    // either way because any of them may be requested at runtime.
    name: 'openframe-frontend-core/icon-registry-is-a-namespace',
    files: ['src/components/chat/utils/icon-library.tsx'],
    rules: { 'import/no-namespace': 'off' },
  },

  {
    // `no-node-access` / `no-container` encode "test what the user sees, not
    // the markup". That is right for a component test and wrong for these four,
    // where the DOM *is* the unit under test and a semantic query cannot
    // express the assertion at all:
    //   - markdown-parity: golden HTML for the markdown renderer. The contract
    //     is the emitted tree (heading ids in document order, innerHTML vs a
    //     snapshot), which `getByRole` has no vocabulary for.
    //   - sanitize-render: the XSS sanitizer. "Did a <script> node survive"
    //     and "was the onerror attribute stripped" are questions about nodes
    //     the user must NEVER see — an accessible query would find nothing and
    //     pass while the payload sat in the DOM.
    //   - embed-viewer-frame: an explicit structural parity pin for the
    //     EmbedViewerFrame extraction. Coupling to wrapper classes and iframe
    //     attributes is the stated purpose of the file, not an accident.
    //   - streaming: asserts NODE IDENTITY across re-renders
    //     (`Object.is(container.querySelector('p'), firstParagraph)`) to prove
    //     completed blocks stay memoized. A fresh query returns the element but
    //     the memo claim is about the node itself.
    // Everything else in the suite was converted to `screen` queries instead
    // of being listed here; adding a fifth file should require the same
    // argument, which is why this is an explicit list and not a glob.
    name: 'openframe-frontend-core/dom-is-the-unit-under-test',
    files: [
      'src/components/ui/__tests__/markdown-parity.test.tsx',
      'src/components/ui/markdown/__tests__/sanitize-render.test.tsx',
      'src/components/ui/markdown/__tests__/streaming.test.tsx',
      'src/components/embeds/__tests__/embed-viewer-frame.test.tsx',
    ],
    rules: {
      'testing-library/no-node-access': 'off',
      'testing-library/no-container': 'off',
    },
  },

  {
    // `no-manual-cleanup` is right that RTL cleans up on its own — but it
    // assumes the ONLY thing that matters is that cleanup happens, not WHEN.
    // This suite stubs `globalThis.WebSocket` in `beforeEach` and restores it
    // in `afterEach`. RTL registers its auto-cleanup at import time, and Vitest
    // stacks `afterEach` hooks in reverse registration order, so the auto
    // cleanup runs AFTER this file's — i.e. after the real WebSocket is back.
    // A retry timer still armed at that point would dial jsdom's real socket.
    // The explicit `cleanup()` unmounts first, which is the whole point.
    //
    // `react-hooks/immutability` is off for the same file: the harness
    // publishes its `setToken` / `setChatOpen` onto the `controls` object the
    // test passes in, from inside an effect, so the test can drive the
    // component from outside. That is a prop mutation by construction — the
    // alternative is a forwardRef + useImperativeHandle ceremony around a
    // throwaway harness.
    name: 'openframe-frontend-core/ordered-teardown',
    files: ['src/nats/__tests__/reconnect-lifecycle.test.tsx'],
    rules: {
      'testing-library/no-manual-cleanup': 'off',
      'react-hooks/immutability': 'off',
    },
  },

  {
    // `no-control-regex` assumes a control character in a pattern is a typo
    // (`\x1b` where `\e` was meant). These three modules are the exceptions
    // where matching them IS the job:
    //   - encode.ts frames SSE on \0 / \x1E / \x1F and must strip those bytes
    //     out of model text before they reach the wire;
    //   - sanitize.ts and compact-card-classes.ts reject `\x00-\x1f` inside a
    //     URL because that is how `java\x00script:` slips past a naive scheme
    //     check.
    // Rewriting the ranges to dodge the rule would make three security-relevant
    // regexes harder to read, so the exception is declared here where it can be
    // reviewed.
    name: 'openframe-frontend-core/control-chars-are-the-payload',
    files: [
      'src/chat-protocol/encode.ts',
      'src/components/ui/markdown/sanitize.ts',
      'src/components/chat/utils/compact-card-classes.ts',
    ],
    rules: { 'no-control-regex': 'off' },
  },

  {
    // `no-img-element` is on for a reason (§ header) and 24 raw `<img>` tags in
    // this library were converted to the `next/image` embed shim. These three
    // are the residue where the rule's premise does not hold — the whole point
    // of `next/image` is an optimizer fetching the source, and none of these
    // sources can be fetched:
    //   - next-image.tsx IS the shim's own `<img>` fallback. Routing it through
    //     itself is infinite recursion.
    //   - chat-attachment-bar renders a `blob:` object URL for a file the user
    //     has not uploaded yet. It exists only in this tab's memory.
    //   - agent-mark renders Fae's avatar, a base64 `data:` URI packaged with
    //     the library, and its contract is that the CALLER sizes it via
    //     `className` — there is no intrinsic width/height to hand `next/image`,
    //     which refuses to render without one.
    // Declared as a named block so the reasoning is reviewable and a new raw
    // `<img>` anywhere else still fails the build.
    name: 'openframe-frontend-core/img-the-optimizer-cannot-fetch',
    files: [
      'src/embed-shims/next-image.tsx',
      'src/components/chat/chat-attachment-bar.tsx',
      'src/components/agent-mark.tsx',
    ],
    rules: { '@next/next/no-img-element': 'off' },
  },

  {
    // ONE finding: the rising-edge theater seed reads `resumeHandleRef` during
    // render (~line 582). It has to. `resumeMode` collapses in this very render,
    // so `VideoHoverPreviewSurface` re-keys its inner <Video> and the mini
    // player's `useImperativeHandle` cleanup nulls the ref in THIS commit's
    // mutation phase — before any layout effect in this component runs. Measured:
    // render sees resumeHandle=200, a layout effect sees null. The layout-effect
    // version was built and tested: the theater reopens from the stale stored
    // handoff instead of the live mini-player position. Render is the last point
    // at which that player is readable at all. The only alternative is plumbing a
    // `timeupdate` mirror through Video -> VideoHoverPreviewSurface, trading
    // exactness for ~250ms staleness — a redesign, not a lint fix.
    //
    // This block used to cover 37 findings on a DIFFERENT and false premise:
    // that MuxPlayer is constructed in the render that flips `open`, making an
    // effect "one render too late". It is not — Radix `Presence` only dispatches
    // MOUNT from its own layout effect, so the player is built one render after
    // the flip either way. The other 36 moved to a layout effect and a pure
    // seed helper on 2026-08-25, with no set-state-in-effect debt traded for it.
    name: 'openframe-frontend-core/render-phase-media-handoff',
    files: ['src/components/features/walkthrough-video.tsx'],
    rules: { 'react-hooks/refs': 'off' },
  },

  {
    // `renderItem(item, { rootRef: getCardRef(i), ... })` is a render prop called
    // during render, and the compiler flags any ref-carrying closure passed to a
    // call it cannot see into. Verified by probe that the ref callback alone
    // triggers it, so decoupling the handlers would not help. Passing a callback
    // ref through a render prop is the correct pattern; the alternative is
    // redesigning the per-card IntersectionObserver registration.
    name: 'openframe-frontend-core/ref-through-render-prop',
    files: ['src/components/features/cards-strip.tsx'],
    rules: { 'react-hooks/refs': 'off' },
  },

  {
    // Two host-injection slots: the lib holds an unvalidated row and only the
    // EMBEDDER can name its type. Every alternative was compiled against the real
    // consumers, not argued:
    //   - related-content-section `AdminCampaignCardSlot.Card`, vs the hub's
    //     `CampaignCardAdmin`: `unknown` blocks host injection (TS2322); `never`
    //     blocks the rail from handing it a row (TS2769); a generic on the slot's
    //     owner infers from the host's card but still cannot render (TS2769,
    //     "'TCampaign' could be instantiated with an arbitrary type").
    //   - tab-navigation `TabItem.component`, vs two live openframe-oss-frontend
    //     patterns that demand OPPOSITE defaults for a generic `TabItem<P>`:
    //     `ComponentType<{scheduleId: string}>` in a `TabItem[]` needs `P = never`,
    //     while `<TabComponent />` with no props needs `P = Record<string, never>`.
    //     Each default rejects the other call site (TS2322 / TS2769+TS2786).
    // Typing either one means changing the injection contract and breaking every
    // embedder — a product decision, not a lint fix. The reasoning is also in each
    // declaration's docblock.
    //
    // The runtime-keyed card dispatch that used to be exempted here is GONE: it
    // moved to src/components/related-content/card-registry.tsx (2026-08-25),
    // which carries each type's own row type and needs no exemption.
    name: 'openframe-frontend-core/host-injection-slots',
    files: ['src/components/related-content/related-content-section.tsx', 'src/components/ui/tab-navigation.tsx'],
    rules: { '@typescript-eslint/no-explicit-any': 'off' },
  },

  {
    // The rule's own message endorses "update external systems with the latest
    // state from React" — these three effects do exactly that, and the setState
    // is bookkeeping around the external call, not derivable during render:
    //   - video.tsx drives the HTMLMediaElement; the mute fallbacks are written
    //     in response to what play() actually permits, unknowable at render time.
    //   - figma-prototype-viewer postMessages the iframe to navigate.
    //   - use-nats-chat-adapter kicks off loadDialogHistory.
    // Verified by probe that the rule flags any TRANSITIVE setState from an effect
    // body regardless of `await`, so the only way to clear these is to duplicate
    // each controller inside its effect — which would break the uncontrolled
    // mouse-handler path in video.tsx and, in the adapter, restructure the chat
    // pipeline for zero lint benefit.
    name: 'openframe-frontend-core/imperative-external-systems',
    files: [
      'src/components/features/video.tsx',
      'src/components/features/figma-prototype-viewer.tsx',
      'src/components/chat/hooks/use-nats-chat-adapter.ts',
    ],
    rules: { 'react-hooks/set-state-in-effect': 'off' },
  },

  ...prettierCompat,
]);
