import { defineConfig } from 'tsup'

// Config is split into two builds: client and server/universal.
//
// Problem: tsup bundles all barrel re-exports into a single file and strips
// "use client" directives from individual source files. Components like
// ToggleGroup call createContext() at the module top level. When Next.js
// server code transitively imports a barrel (e.g. components/ui), the entire
// bundle executes on the server where createContext doesn't exist — causing
// "createContext is not a function" errors.
//
// Solution: client entries use `banner` to inject "use client" as the first
// line of every output file. Note: `banner` is incompatible with `treeshake`
// (rollup strips it), so client entries don't use treeshake and server
// entries don't use banner.
//
// Declarations: Generated by tsc (not tsup) to produce .d.ts.map files for
// source navigation. See tsconfig.declarations.json and build script.
//
// The dist/ directory is cleaned by the build script (rm -rf dist) before
// tsup runs, so neither config needs `clean: true`.

export default defineConfig([
  // Server/universal entries — pure types, configs, and server-safe utilities.
  // No "use client" needed; treeshake enabled to reduce bundle size.
  {
    entry: {
      'types/index': 'src/types/index.ts',
      'types/navigation': 'src/types/navigation.ts',
      'types/announcement': 'src/types/announcement.ts',
      'assets/index': 'src/assets/index.ts',
      'fonts': 'src/fonts.ts',
      'tailwind.config': './tailwind.config.ts',
      'utils/index': 'src/utils/index.ts',
      // Humanity signals — pure + server-safe (no React, no browser APIs).
      // Its own entry so the hub's server-side `verifyHuman` can import
      // `./utils/humanity-signals` without pulling the full utils barrel.
      'utils/humanity-signals': 'src/utils/humanity-signals.ts',
      // Zod schema — server-safe (no React, no browser APIs). Used by
      // BOTH the lib's `<ContactForm>` for validation AND the hub's
      // server-side /api/contact + admin routes for payload validation.
      'schemas/contact-schema': 'src/schemas/contact-schema.ts',
      // Mux CDN origins — string constants, no React, no browser APIs.
      // Server-safe so hub server-side modules (mux-config, webhook
      // handlers, URL parsers) can import without Next.js client-
      // reference poisoning. The `'use client'` `use-video-warmup.ts`
      // module re-exports these for backward-compat with client-side
      // callers; new server-side callers should import from this
      // subpath directly.
      'components/features/mux-origins': 'src/components/features/mux-origins.ts',
      // Platform-domain SSOT — pure, zero-dep, edge-safe (no React, no browser
      // APIs, no server-only). Its own entry so the hub's Edge middleware
      // (proxy.ts) + cors.ts can import `hostOf`/`expandWwwApex`/`isPreviewEnv`
      // without pulling the full utils barrel into the Edge bundle.
      'platform-domains': 'src/platform-domains.ts',
      // FAQ JSON-LD builder — pure (no React, no browser APIs), so Server
      // Components in consumers can import it via the './components/faq/json-ld'
      // subpath WITHOUT crossing the "use client" boundary that the sibling
      // './components/faq' (FaqSection) subpath carries. Source filename
      // matches the entry key (`json-ld.ts`) so tsc-emitted `.d.ts` and
      // tsup-emitted `.js`/`.cjs` land at the SAME `dist/components/faq/json-ld.*`
      // paths that `package.json#exports` references — without this match the
      // subpath resolves at runtime but TypeScript sees "no exported member".
      'components/faq/json-ld': 'src/components/faq/json-ld.ts',
      // Doc-source viewer types — pure interfaces, no React. Server-safe
      // subpath so the hub's `lib/config/doc-sources.ts` can import without
      // crossing the "use client" boundary on the components/docs barrel.
      'types/doc-source': 'src/types/doc-source.ts',
    },
    format: ['esm', 'cjs'],
    dts: false,
    splitting: false,
    sourcemap: true,
    external: ['react', 'react-dom', 'next', '@tanstack/react-query'],
    treeshake: true,
  },
  // Client-side entries — these contain React components/hooks that require
  // browser APIs. The "use client" banner tells Next.js to treat the entire
  // bundle as a Client Component boundary.
  {
    entry: {
      'index': 'src/index.ts',
      'nats/index': 'src/nats/index.ts',
      'components/index': 'src/components/index.ts',
      'components/ui/index': 'src/components/ui/index.ts',
      'components/chat/index': 'src/components/chat/index.ts',
      'components/tickets/index': 'src/components/tickets/index.ts',
      'components/onboarding-guides/index': 'src/components/onboarding-guides/index.ts',
      'components/contact/index': 'src/components/contact/index.ts',
      // FAQ subpath — client-only (FaqSection is a client component). Pure
      // JSON-LD builder lives on a separate server-safe subpath
      // 'components/faq/json-ld' built in the server block above.
      'components/faq/index': 'src/components/faq/index.ts',
      'components/related-content/index': 'src/components/related-content/index.ts',
      'components/ui/file-manager/index': 'src/components/ui/file-manager/index.ts',
      'components/features/index': 'src/components/features/index.ts',
      'components/toast/index': 'src/components/toast/index.ts',
      'components/icons/index': 'src/components/icons/index.ts',
      'components/icons-v2-generated/index': 'src/components/icons-v2-generated/index.ts',
      'components/navigation/index': 'src/components/navigation/index.ts',
      // Doc-viewer subpath — DocViewer + hooks + multi-navigator context +
      // markdown/rich content renderers. Lifted from the hub during the
      // doc-viewer unification.
      'components/docs/index': 'src/components/docs/index.ts',
      // Embed subpath — PDF / Google Sheets / Figma / iframe wrappers.
      // Lifted alongside the doc viewer; also consumed by hub admin
      // (document-editor) and blog markdown renderer (FigmaEmbed).
      'components/embeds/index': 'src/components/embeds/index.ts',
      'hooks/index': 'src/hooks/index.ts',
      'contexts/index': 'src/contexts/index.ts',
      // Embed shims — registration-pattern wrappers for next/dynamic, next/link,
      // next/image, and next/navigation. Each is built as its own entry so
      // consumers can deep-import (`embed-shims/next-image`) without pulling
      // the whole barrel. Hub also imports the barrel for the `register*`
      // functions in its app-init wiring.
      'embed-shims/index': 'src/embed-shims/index.ts',
      'embed-shims/next-image': 'src/embed-shims/next-image.tsx',
      'embed-shims/next-link': 'src/embed-shims/next-link.tsx',
      'embed-shims/next-dynamic': 'src/embed-shims/next-dynamic.tsx',
      'embed-shims/next-navigation': 'src/embed-shims/next-navigation.tsx',
    },
    format: ['esm', 'cjs'],
    dts: false,
    splitting: true,
    sourcemap: true,
    external: ['react', 'react-dom', 'next', '@tanstack/react-query'],
    banner: {
      js: '"use client";',
    },
  },
])
