import { defineConfig } from 'tsup'

// Config is split into two builds: client and server/universal.
//
// Problem: tsup bundles all barrel re-exports into a single file and strips
// "use client" directives from individual source files. Components like
// ToggleGroup call createContext() at the module top level. When Next.js
// server code transitively imports a barrel (e.g. components/ui), the entire
// bundle executes on the server where createContext doesn't exist — causing
// "createContext is not a function" errors.
//
// Solution: client entries use `banner` to inject "use client" as the first
// line of every output file. Note: `banner` is incompatible with `treeshake`
// (rollup strips it), so client entries don't use treeshake and server
// entries don't use banner.
//
// Declarations: Generated by tsc (not tsup) to produce .d.ts.map files for
// source navigation. See tsconfig.declarations.json and build script.
//
// The dist/ directory is cleaned by the build script (rm -rf dist) before
// tsup runs, so neither config needs `clean: true`.

export default defineConfig([
  // Server/universal entries — pure types, configs, and server-safe utilities.
  // No "use client" needed; treeshake enabled to reduce bundle size.
  {
    entry: {
      'types/index': 'src/types/index.ts',
      'types/navigation': 'src/types/navigation.ts',
      'types/announcement': 'src/types/announcement.ts',
      'assets/index': 'src/assets/index.ts',
      'fonts': 'src/fonts.ts',
      'tailwind.config': './tailwind.config.ts',
      'utils/index': 'src/utils/index.ts',
      // Zod schema — server-safe (no React, no browser APIs). Used by
      // BOTH the lib's `<ContactForm>` for validation AND the hub's
      // server-side /api/contact + admin routes for payload validation.
      'schemas/contact-schema': 'src/schemas/contact-schema.ts',
    },
    format: ['esm', 'cjs'],
    dts: false,
    splitting: false,
    sourcemap: true,
    external: ['react', 'react-dom', 'next', '@tanstack/react-query'],
    treeshake: true,
  },
  // Client-side entries — these contain React components/hooks that require
  // browser APIs. The "use client" banner tells Next.js to treat the entire
  // bundle as a Client Component boundary.
  {
    entry: {
      'index': 'src/index.ts',
      'nats/index': 'src/nats/index.ts',
      'components/index': 'src/components/index.ts',
      'components/ui/index': 'src/components/ui/index.ts',
      'components/chat/index': 'src/components/chat/index.ts',
      'components/tickets/index': 'src/components/tickets/index.ts',
      'components/onboarding-guides/index': 'src/components/onboarding-guides/index.ts',
      'components/contact/index': 'src/components/contact/index.ts',
      'components/ui/file-manager/index': 'src/components/ui/file-manager/index.ts',
      'components/features/index': 'src/components/features/index.ts',
      'components/toast/index': 'src/components/toast/index.ts',
      'components/icons/index': 'src/components/icons/index.ts',
      'components/icons-v2-generated/index': 'src/components/icons-v2-generated/index.ts',
      'components/navigation/index': 'src/components/navigation/index.ts',
      'hooks/index': 'src/hooks/index.ts',
      'contexts/index': 'src/contexts/index.ts',
      // Embed shims — registration-pattern wrappers for next/dynamic, next/link,
      // next/image, and next/navigation. Each is built as its own entry so
      // consumers can deep-import (`embed-shims/next-image`) without pulling
      // the whole barrel. Hub also imports the barrel for the `register*`
      // functions in its app-init wiring.
      'embed-shims/index': 'src/embed-shims/index.ts',
      'embed-shims/next-image': 'src/embed-shims/next-image.tsx',
      'embed-shims/next-link': 'src/embed-shims/next-link.tsx',
      'embed-shims/next-dynamic': 'src/embed-shims/next-dynamic.tsx',
      'embed-shims/next-navigation': 'src/embed-shims/next-navigation.tsx',
    },
    format: ['esm', 'cjs'],
    dts: false,
    splitting: true,
    sourcemap: true,
    external: ['react', 'react-dom', 'next', '@tanstack/react-query'],
    banner: {
      js: '"use client";',
    },
  },
])
