name: CI Release

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [feature/ci_release]

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Get Next Version
        id: version
        run: |
          # Fetch latest version from registry
          URL="https://maven.pkg.github.com/flamingo-stack/openframe-oss-lib"
          METADATA=$(curl -sf -H "Authorization: token ${{ github.token }}" \
            "$URL/com/openframe/oss/openframe-data-mongo/maven-metadata.xml" 2>/dev/null || echo "")
          
          # Extract latest version or use default
          if [ -n "$METADATA" ]; then
            LATEST=$(echo "$METADATA" | grep -oP '<version>\K[0-9]+\.[0-9]+\.[0-9]+' | sort -V | tail -1)
          fi
          LATEST=${LATEST:-1.0.0}
          
          # Increment patch version
          IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST"
          NEW_VERSION="${MAJOR}.${MINOR}.$((PATCH + 1))-PR${{ github.event.pull_request.number }}-SNAPSHOT"
          
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "📦 Version: $NEW_VERSION (previous: $LATEST)"
      
      - name: Set Version
        run: mvn versions:set -DnewVersion="${{ steps.version.outputs.version }}" -DgenerateBackupPoms=false
      
      - name: Build & Test
        run: mvn clean verify
      
      - name: Deploy
        run: mvn deploy -DskipTests -s .mvn/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Summary
        if: always()
        run: |
          cat >> $GITHUB_STEP_SUMMARY << EOF
          ## 📦 CI Release: \`${{ steps.version.outputs.version }}\`
          
          **PR #${{ github.event.pull_request.number }}** • ${GITHUB_SHA:0:7}
          
          ### Published to GitHub Packages:
          - com.openframe.oss:openframe-data-mongo
          - com.openframe.oss:openframe-test-lib
          EOF