name: Publish OSS Libs to GitHub Packages

on:
  push:
    branches:
      - 'test/**'
      - 'feature/**'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version from POM (${revision})
        id: read-version
        run: |
          VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=revision || true)
          if [ -z "$VERSION" ]; then VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version); fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Assert tag matches POM version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          if [ "v${VERSION}" != "${GITHUB_REF_NAME}" ]; then
            echo "Tag ${GITHUB_REF_NAME} != v${VERSION}"; exit 1;
          fi

      - name: Build only (branches)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: mvn -B -ntp -DskipTests install

      - name: Deploy on tags
        if: startsWith(github.ref, 'refs/tags/')
        run: mvn -B -ntp -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
